/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groovy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AdditionOperationTest { 
@Test 
public void testAddition() { 
double num1 = 5; 
double num2 = 10; 
double expectedSum = num1 + num2; 
double actualSum = num1 + num2; 
assertEquals(expectedSum, actualSum, 0.01); 
} 
}
